# grog.package
package_list:
  - name: bash-completion
  - name: curl
  - name: dnsutils
  - name: htop
  - name: net-tools
  - name: nmap
  - name: wget
  - name: pipx
  - name: git
  - name: just

# ironicbadger.bash-aliases
bash_aliases:
  - { alias: "dtail", command: "docker logs -tf --tail='50' " }
  - { alias: "dup", command: "docker-compose -f ~/docker-compose.yml -d " }
  - { alias: "dclean", command: "docker system prune --all" }
  - { alias: "dtop", command: "docker run --name ctop  -it --rm -v /var/run/docker.sock:/var/run/docker.sock quay.io/vektorlab/ctop" }  
  - { alias: "gadd", command: "git add ." }  
  - { alias: "gm", command: "git commit -m " }  